### ISSUE TITLE
Missing LICENSE.txt

### ISSUE THREAD

**Issue by justwheel** [WillNilges/DNDNV#8]
Hi! This repository does not have a license. This means that the code, by default, falls under U.S. copyright law. This is very restrictive! The [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause) is a favorite of mine, but [choosealicense.com](https://choosealicense.com/) is a good place to start if you want to see what is out there.

**Comment by WillNilges** [comment]
Fixed in #12
